version: '3.8'

services:
  backend:
    build: ./backend
    container_name: demo_backend
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: demo_frontend
    restart: unless-stopped
    expose:
      - 80
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    container_name: demo_nginx
    restart: unless-stopped
    ports:
      - "8080:80"  # Puerto expuesto al host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
